// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import ar from './ar'
import de from './de'
import en from './en'
import es from './es'
import fr from './fr'
import hi from './hi'
import ja from './ja'
import ko from './ko'
import pt from './pt'
import ru from './ru'
import zh_HanS from './zh-HanS'
import zh_HanT from './zh-HanT'

const localeTranslations = {
	ar,
	de,
	en,
	es,
	fr,
	hi,
	ja,
	ko,
	pt,
	ru,
	'zh-HanS': zh_HanS,
	'zh-HanT': zh_HanT,
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
