// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import ain from './ain'
import ar from './ar'
import bn from './bn'
import de from './de'
import en from './en'
import eo from './eo'
import es from './es'
import fa from './fa'
import fr from './fr'
import grc from './grc'
import hi from './hi'
import ia from './ia'
import id from './id'
import it from './it'
import ja from './ja'
import ja_Hira from './ja-Hira'
import ko from './ko'
import ko_Kore from './ko-Kore'
import la from './la'
import nl from './nl'
import pl from './pl'
import pt from './pt'
import ru from './ru'
import th from './th'
import tok from './tok'
import tr from './tr'
import uk from './uk'
import ur from './ur'
import vi from './vi'
import zh_HanS from './zh-HanS'
import zh_HanT from './zh-HanT'

const localeTranslations = {
	ain,
	ar,
	bn,
	de,
	en,
	eo,
	es,
	fa,
	fr,
	grc,
	hi,
	ia,
	id,
	it,
	ja,
	'ja-Hira': ja_Hira,
	ko,
	'ko-Kore': ko_Kore,
	la,
	nl,
	pl,
	pt,
	ru,
	th,
	tok,
	tr,
	uk,
	ur,
	vi,
	'zh-HanS': zh_HanS,
	'zh-HanT': zh_HanT,
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
